// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAVyDAiZMyQc4GGuuzSn3ItV9w02SsqDA',
    appId: '1:742248575431:web:294e926c7a97ad6fde29e2',
    messagingSenderId: '742248575431',
    projectId: 'socialmediaapp-cbe00',
    authDomain: 'socialmediaapp-cbe00.firebaseapp.com',
    storageBucket: 'socialmediaapp-cbe00.firebasestorage.app',
    measurementId: 'G-ECBSTWHVG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADKqw5mczNU7QQUcLxhVA2F_SCxyoC3kI',
    appId: '1:742248575431:android:9675e537ae4207afde29e2',
    messagingSenderId: '742248575431',
    projectId: 'socialmediaapp-cbe00',
    storageBucket: 'socialmediaapp-cbe00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiaOiIp4MN6lQznweEMxwEgMTorEX6nVo',
    appId: '1:742248575431:ios:3ac7be5395a15d10de29e2',
    messagingSenderId: '742248575431',
    projectId: 'socialmediaapp-cbe00',
    storageBucket: 'socialmediaapp-cbe00.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiaOiIp4MN6lQznweEMxwEgMTorEX6nVo',
    appId: '1:742248575431:ios:3ac7be5395a15d10de29e2',
    messagingSenderId: '742248575431',
    projectId: 'socialmediaapp-cbe00',
    storageBucket: 'socialmediaapp-cbe00.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAVyDAiZMyQc4GGuuzSn3ItV9w02SsqDA',
    appId: '1:742248575431:web:317cd6bf7c41bb4dde29e2',
    messagingSenderId: '742248575431',
    projectId: 'socialmediaapp-cbe00',
    authDomain: 'socialmediaapp-cbe00.firebaseapp.com',
    storageBucket: 'socialmediaapp-cbe00.firebasestorage.app',
    measurementId: 'G-VBTTBF6YMX',
  );
}
